### PR TITLE
SentimentNet_XJY_ZJUT

### PR DESCRIPTION
**Pull request by zjuter0126**
SentimentNet 更新 参照来源-->mindspore
具体使用请查看sentimentnet.md

### CODE REVIEW

**Comment by leonwanghui** [comment]
@zjuter0126 Could u add the `download_dataset` method for the LSTM dataset, or specify it in the document.

**Comment by zjuter0126** [comment]
> @zjuter0126 Could u add the `download_dataset` method for the LSTM dataset, or specify it in the document.

I have update the sentimentnet and upload glove_path.jpg and acllmdb_path.jpg to specify the way to download_dataset.

**Comment by leonwanghui** [comment]
@zjuter0126 If so, I suggest you could add a new `***Dataset` in data module, so that users could directly call this function in other network.

**Comment by zjuter0126** [comment]
> @zjuter0126 If so, I suggest you could add a new `***Dataset` in data module, so that users could directly call this function in other network.
I have add my imdb.py into tinyms/data file ,it can run in my enviroment.However, it show my pr failed,it can't pass the check.

**Comment by zjuter0126** [comment]
> > @zjuter0126 If so, I suggest you could add a new `***Dataset` in data module, so that users could directly call this function in other network.
> > I have add my imdb.py into tinyms/data file ,it can run in my enviroment.However, it show my pr failed,it can't pass the check.

I find it lack of the lib gensim.I add it into the requriment.txt and it seems to work well.

**Comment by leonwanghui** [comment]
@zjuter0126 Overall LGTM, but could u remove all the image files and correct some pylint warning? Thanks!

**Comment by zjuter0126** [comment]
> @zjuter0126 Overall LGTM, but could u remove all the image files and correct some pylint warning? Thanks!

I find the source of warnings comes from mindspore==1.1.1,when I use mindspore_gpu==1.2.0rc1,they disapear.You can download it by
'''
pip install https://ms-release.obs.cn-north-4.myhuaweicloud.com/1.2.0-rc1/MindSpore/gpu/ubuntu_x86/cuda-10.1/mindspore_gpu-1.2.0rc1-cp37-cp37m-linux_x86_64.whl --trusted-host ms-release.obs.cn-north-4.myhuaweicloud.com -i https://pypi.tuna.tsinghua.edu.cn/simple
'''
You can see the warnings disapear.

**Comment by zjuter0126** [comment]
> > @zjuter0126 Overall LGTM, but could u remove all the image files and correct some pylint warning? Thanks!
> 
> I find the source of warnings comes from mindspore==1.1.1,when I use mindspore_gpu==1.2.0rc1,they disapear.You can download it by
> '''
> pip install https://ms-release.obs.cn-north-4.myhuaweicloud.com/1.2.0-rc1/MindSpore/gpu/ubuntu_x86/cuda-10.1/mindspore_gpu-1.2.0rc1-cp37-cp37m-linux_x86_64.whl --trusted-host ms-release.obs.cn-north-4.myhuaweicloud.com -i https://pypi.tuna.tsinghua.edu.cn/simple
> '''
> You can see the warnings disapear.

**Comment by zjuter0126** [comment]
> > > @zjuter0126 Overall LGTM, but could u remove all the image files and correct some pylint warning? Thanks!
> > 
> > 
> > I find the source of warnings comes from mindspore==1.1.1,when I use mindspore_gpu==1.2.0rc1,they disapear.You can download it by
> > '''
> > pip install https://ms-release.obs.cn-north-4.myhuaweicloud.com/1.2.0-rc1/MindSpore/gpu/ubuntu_x86/cuda-10.1/mindspore_gpu-1.2.0rc1-cp37-cp37m-linux_x86_64.whl --trusted-host ms-release.obs.cn-north-4.myhuaweicloud.com -i https://pypi.tuna.tsinghua.edu.cn/simple
> > '''
> > You can see the warnings disapear.



> > > @zjuter0126 Overall LGTM, but could u remove all the image files and correct some pylint warning? Thanks!
> > 
> > 
> > I find the source of warnings comes from mindspore==1.1.1,when I use mindspore_gpu==1.2.0rc1,they disapear.You can download it by
> > '''
> > pip install https://ms-release.obs.cn-north-4.myhuaweicloud.com/1.2.0-rc1/MindSpore/gpu/ubuntu_x86/cuda-10.1/mindspore_gpu-1.2.0rc1-cp37-cp37m-linux_x86_64.whl --trusted-host ms-release.obs.cn-north-4.myhuaweicloud.com -i https://pypi.tuna.tsinghua.edu.cn/simple
> > '''
> > You can see the warnings disapear.

I

**Comment by zjuter0126** [comment]
> > > @zjuter0126 Overall LGTM, but could u remove all the image files and correct some pylint warning? Thanks!
> > 
> > 
> > I find the source of warnings comes from mindspore==1.1.1,when I use mindspore_gpu==1.2.0rc1,they disapear.You can download it by
> > '''
> > pip install https://ms-release.obs.cn-north-4.myhuaweicloud.com/1.2.0-rc1/MindSpore/gpu/ubuntu_x86/cuda-10.1/mindspore_gpu-1.2.0rc1-cp37-cp37m-linux_x86_64.whl --trusted-host ms-release.obs.cn-north-4.myhuaweicloud.com -i https://pypi.tuna.tsinghua.edu.cn/simple
> > '''
> > You can see the warnings disapear.

And I add it into my branch.You can see it in 1.1.1.jpg and 1.2.0.jpg

**Comment by leonwanghui** [comment]
@zjuter0126 Got it, we will upgrade mindpore to `v1.2.0` sometime later after it being published, so if you can remove the binary pictures, I guess this PR could be merged.

**Comment by leonwanghui** [comment]
@zjuter0126 BTW, could u append the instruction of training and evaluation guidelines in the comments of your PR? So other developers could follow it, thanks!

**Comment by zjuter0126** [comment]
> @zjuter0126 BTW, could u append the instruction of training and evaluation guidelines in the comments of your PR? So other developers could follow it, thanks!

As you suggest,I add training and evaluate guidelines in test/st/sentiment.py  and put test file sentimentnet.py into it.And I also delete 1.1.1.jpg and 1.2.0.jpg.

**Comment by leonwanghui** [comment]
@zjuter0126 It seems that the evaluation code doesn't work, could u share some guidelines? Thanks!

**Comment by leonwanghui** [comment]
@zjuter0126 I found the issue, which is that `--preprocess` is not required because `aclImdb_train.mindrecord0` and `aclImdb_test.mindrecord0` are both created during training step, so `--preprocess` (even `--aclimdb_path` and `--glove_path`) should be removed.

BTW, the `--checkpoint_path` is missing in the guideline.

**Comment by zjuter0126** [comment]
> @zjuter0126 I found the issue, which is that `--preprocess` is not required because `aclImdb_train.mindrecord0` and `aclImdb_test.mindrecord0` are both created during training step, so `--preprocess` (even `--aclimdb_path` and `--glove_path`) should be removed.
> 
> BTW, the `--checkpoint_path` is missing in the guideline.

Thanks for your suggestions.I correct my preprocess ways so it can work well when preprocessed data have been create.Even though, maybe it is not so beautiful.

**Review by leonwanghui — APPROVED** [review]
LGTM

**Review by hannibalhuang — APPROVED** [review]
LGTM

**Pull request merged**
