### PR TITLE
DenseNetBC100

### PR DESCRIPTION
**Pull request by huicui1996**
I have finished DenseNetBC100 for cifar10,please use python train.py to verify the code,details could be seen in readme.md

### CODE REVIEW

**Comment by leonwanghui** [comment]
@huicui1996 Please sign the CLA firstly

**Comment by huicui1996** [comment]
> @huicui1996 Please sign the CLA firstly

Ok.I have signed the CLA.

**Comment by leonwanghui** [comment]
@huicui1996 您好 很高兴地宣布您跑通DenseNet100模型流程的时间（`2021-04-01-16:51`）在所有参赛选手中位居第二位，满足二等奖的条件（TOP3）

**Comment by hellowaywewe** [comment]
活动已结束，关闭

**Pull request closed without merging**
