### PR TITLE
Alexnet TinyMs XJY

### PR DESCRIPTION
**Pull request by zjuter0126**
加入了alexnet   运行请见alexnet.md

### CODE REVIEW

**Comment by leonwanghui** [comment]
@zjuter0126 Some tiny errors mentioned above

**Comment by zjuter0126** [comment]
> @zjuter0126 Some tiny errors mentioned above

I have corrected my errors mentioned above.

**Comment by leonwanghui** [comment]
@zjuter0126 Got it, I'm testing your PR locally to see if they are working well, please hold a minute : )

**Review by leonwanghui — APPROVED** [review]
LGTM

**Comment by huxiaoman7** [comment]
LGTM

**Review by huxiaoman7 — DISMISSED** [review]

**Comment by zjuter0126** [comment]
> LGTM
Thank you, the code for densenet is similar to alexnet, you can run it in a similar way.

**Comment by leonwanghui** [comment]
@zjuter0126 Please remove the `*.md` and `*.png` file under the root folder, then this PR would be getting merged.

**Review by leonwanghui — APPROVED** [review]
LGTM

**Comment by huxiaoman7** [comment]
LGTM

**Review by huxiaoman7 — APPROVED** [review]

**Review by huxiaoman7 — APPROVED** [review]

**Pull request merged**
