### PR TITLE
Realize graphic application tinyms in one minute Version update for 3.0

### PR DESCRIPTION
**Pull request by xinwenh**
**What type of PR is this?**

> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:tinyms0. 3.0 running on jupyter>
> `/kind bug`</br>
> `/kind enhancement`</br>
> `/kind documentation`</br>

**What does this PR do / why do we need it**:
Improved the update of OPT, server and client interface problems. PIP install tinyms0.3.1 before installation package, start_ Change server to server start_ server,list_ Change servables() to client list_ servables(),Change predict() to client predict().It is done for version update

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewers**:

### CODE REVIEW

**Comment by lwdragon** [comment]
Thank you for your submission! Please sign our Contributor License Agreement before we can accept your contribution.

**Comment by lwdragon** [comment]
Hi, @xinwenh, I see here you signed the CLA, and I see you are a First-time GitHub contributor, thanks again for the pr.
you have some problems with your first pr：
1. Your commit description is not accurate and concise enough
2. You need to change the introduction of your pr again, you need to clarify what type of pr you are, and simply clear what your pr does, you can list the pr tasks you do by serial number, and this The side suggests that you can mention an Issues and then link it through the anchor point in the Pr profile

**Comment by lwdragon** [comment]
Hi, @xinwenh, I see here you signed the CLA, and I see you are a First-time GitHub contributor, thanks again for the pr.
you have some problems with your first pr：
1. Your commit description is not accurate and concise enough
2. You need to change the introduction of your pr again, you need to clarify what type of pr you are, and simply clear what your pr does, you can list the pr tasks you do by serial number, and this The side suggests that you can mention an Issues and then link it through the anchor point in the Pr profile

**Comment by lwdragon** [comment]
Hi, @xinwenh, I have seen two commits on your side, but the tasks are the same, I suggest you merge them

**Comment by xinwenh** [comment]
> Hi, @xinwenh, I have seen two commits on your side, but the tasks are the same, I suggest you merge them
Thank you for your hint，I will improve it。

**Comment by xinwenh** [comment]
Sorry, it needs to be closed because multiple duplicate PR's have been submitted

**Pull request closed without merging**
